# my global config
global:
  scrape_interval: 1m
  scrape_timeout: 55s
   # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 45s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
# alerting:
#   alertmanagers:
#   - static_configs:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'PCs'
    metrics_path: /metrics
    static_configs:
    - targets: [ 'ip:9182']
      labels: 
        instance: 'label'    
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels: 
          instance: 'prometheus'
  - job_name: pi
    static_configs:
      - targets: ['localhost:9100']
        labels: 
          instance: 'pi'
  - job_name: 'speedtest'
    metrics_path: /probe
    params:
      script: [speedtest]
    static_configs:
      - targets: ['localhost:9469']
    scrape_interval: 60m
    scrape_timeout: 90s
  - job_name: 'script_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9469']
